const fifaToIso2: Record<string, string> = {
  AGO: "AO",
  ARE: "AE",
  ARG: "AR",
  AUS: "AU",
  AUT: "AT",
  BEL: "BE",
  BGR: "BG",
  BIH: "BA",
  BOL: "BO",
  BRA: "BR",
  CAN: "CA",
  CHE: "CH",
  CHL: "CL",
  CHN: "CN",
  CIV: "CI",
  CMR: "CM",
  COD: "CD",
  COL: "CO",
  CRI: "CR",
  CSK: "CZ",
  CZE: "CZ",
  DDR: "DE",
  DEU: "DE",
  DNK: "DK",
  DZA: "DZ",
  ECU: "EC",
  EGY: "EG",
  ESP: "ES",
  FRA: "FR",
  GHA: "GH",
  GRC: "GR",
  HND: "HN",
  HRV: "HR",
  HTI: "HT",
  HUN: "HU",
  IRL: "IE",
  IRN: "IR",
  IRQ: "IQ",
  ISL: "IS",
  ISR: "IL",
  ITA: "IT",
  JAM: "JM",
  JPN: "JP",
  KOR: "KR",
  KWT: "KW",
  MAR: "MA",
  MEX: "MX",
  NGA: "NG",
  NIR: "GB",
  NLD: "NL",
  NOR: "NO",
  NZL: "NZ",
  PAN: "PA",
  PER: "PE",
  POL: "PL",
  PRK: "KP",
  PRT: "PT",
  PRY: "PY",
  QAT: "QA",
  ROU: "RO",
  RUS: "RU",
  SAU: "SA",
  SCG: "RS",
  SEN: "SN",
  SLV: "SV",
  SRB: "RS",
  SUN: "RU",
  SVK: "SK",
  SVN: "SI",
  SWE: "SE",
  TGO: "TG",
  TTO: "TT",
  TUN: "TN",
  TUR: "TR",
  UKR: "UA",
  URY: "UY",
  USA: "US",
  YUG: "RS",
  ZAF: "ZA",
};

const specialFlags: Record<string, string> = {
  ENG: "🏴",
  SCO: "🏴",
  WAL: "🏴",
};

function iso2Flag(countryCode: string) {
  const code = countryCode.toUpperCase();
  if (!/^[A-Z]{2}$/.test(code)) return "🏳";
  return String.fromCodePoint(...[...code].map((char) => 127397 + char.charCodeAt(0)));
}

export function flagForTeamCode(teamCode: string) {
  const code = teamCode.toUpperCase();
  return specialFlags[code] ?? iso2Flag(fifaToIso2[code] ?? code.slice(0, 2));
}
