import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

function loadLocalEnv(path = ".env.local") {
  if (!existsSync(path)) return;
  for (const rawLine of readFileSync(path, "utf8").split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const index = line.indexOf("=");
    if (index === -1) continue;
    const key = line.slice(0, index).trim();
    const value = line.slice(index + 1).trim().replace(/^['"]|['"]$/g, "");
    process.env[key] ||= value;
  }
}

loadLocalEnv();

const outDir = ".da-stack";
mkdirSync(outDir, { recursive: true });
mkdirSync(`${outDir}/client-runtime`, { recursive: true });

const rpc = process.env.OG_RPC_URL || process.env.VITE_OG_RPC_URL || "https://evmrpc-testnet.0g.ai";
const privateKey = process.env.OG_PRIVATE_KEY || "";
const daClientPrivateKey = privateKey.replace(/^0x/i, "");
const daClientPort = process.env.OG_DA_CLIENT_GRPC_PORT || "51001";
const encoderAddress = process.env.OG_DA_ENCODER_ADDRESS || "0g-da-encoder:34000";
const retrieverListen = process.env.OG_DA_RETRIEVER_LISTEN || "0.0.0.0:34005";
const entranceContract = process.env.OG_DA_ENTRANCE_CONTRACT_ADDR || "0x857C0A28A8634614BB2C96039Cf4a20AFF709Aa9";
const signersContract = process.env.OG_DA_SIGNERS_CONTRACT_ADDR || "0x0000000000000000000000000000000000001000";

if (!privateKey) {
  console.warn("Missing OG_PRIVATE_KEY. Generated envfile.env with placeholder PRIVATE_KEY_REQUIRED.");
}

const envfile = `# Generated by scripts/da-stack/prepare.mjs. Do not commit this file.
COMBINED_SERVER_CHAIN_RPC=${rpc}
COMBINED_SERVER_PRIVATE_KEY=${daClientPrivateKey || "PRIVATE_KEY_REQUIRED"}
COMBINED_SERVER_RECEIPT_POLLING_ROUNDS=180
COMBINED_SERVER_RECEIPT_POLLING_INTERVAL=1s
COMBINED_SERVER_TX_GAS_LIMIT=2000000
COMBINED_SERVER_USE_MEMORY_DB=true
COMBINED_SERVER_KV_DB_PATH=/runtime/
COMBINED_SERVER_TimeToExpire=2592000
DISPERSER_SERVER_GRPC_PORT=${daClientPort}
BATCHER_DAENTRANCE_CONTRACT_ADDRESS=${entranceContract}
BATCHER_DASIGNERS_CONTRACT_ADDRESS=${signersContract}
BATCHER_FINALIZER_INTERVAL=20s
BATCHER_CONFIRMER_NUM=3
BATCHER_MAX_NUM_RETRIES_PER_BLOB=3
BATCHER_MAX_NUM_RETRIES_FOR_SIGN=3
BATCHER_FINALIZED_BLOCK_COUNT=50
BATCHER_BATCH_SIZE_LIMIT=500
BATCHER_ENCODING_INTERVAL=3s
BATCHER_ENCODING_REQUEST_QUEUE_SIZE=1
BATCHER_PULL_INTERVAL=10s
BATCHER_SIGNING_INTERVAL=3s
BATCHER_SIGNED_PULL_INTERVAL=20s
BATCHER_EXPIRATION_POLL_INTERVAL=3600
BATCHER_ENCODER_ADDRESS=${encoderAddress}
BATCHER_ENCODING_TIMEOUT=300s
BATCHER_SIGNING_TIMEOUT=60s
BATCHER_CHAIN_READ_TIMEOUT=12s
BATCHER_CHAIN_WRITE_TIMEOUT=13s
`;

const retrieverConfig = `# Generated by scripts/da-stack/prepare.mjs
log_level = "info"
grpc_listen_address = "${retrieverListen}"
eth_rpc_endpoint = "${rpc}"
max_ongoing_retrieve_request = 128
`;

writeFileSync(`${outDir}/envfile.env`, envfile, { mode: 0o600 });
writeFileSync(`${outDir}/retriever-config.toml`, retrieverConfig);
writeFileSync(`${outDir}/README.md`, `# 0G DA local stack

Generated project-local files for 0G World Cup.

- envfile.env: DA Client secret env file. Ignored by git.
- retriever-config.toml: Retriever runtime config.
- client-runtime/: DA Client runtime volume.

Build local images from official repos first:

\\\`\\\`\\\`bash
git clone https://github.com/0gfoundation/0g-da-client.git
cd 0g-da-client
docker build -t 0g-da-client:local -f combined.Dockerfile .

git clone https://github.com/0gfoundation/0g-da-encoder.git
# build/tag as 0g-da-encoder:local using official repo instructions

git clone https://github.com/0gfoundation/0g-da-retriever.git
# build/tag as 0g-da-retriever:local using official repo instructions
\\\`\\\`\\\`

Then from the 0G World Cup project:

\\\`\\\`\\\`bash
docker compose -f scripts/da-stack/docker-compose.0g-da.yml up -d
export OG_DA_CLIENT_GRPC_URL=127.0.0.1:51001
pnpm da:sidecar
pnpm proof:da-sidecar
\\\`\\\`\\\`
`);

console.log(JSON.stringify({
  status: privateKey ? "ready" : "blocked",
  generated: [
    resolve(`${outDir}/envfile.env`),
    resolve(`${outDir}/retriever-config.toml`),
    resolve(`${outDir}/README.md`),
  ],
  reason: privateKey
    ? "Generated project-local 0G DA stack env/config files."
    : "Generated files, but OG_PRIVATE_KEY must be set before DA Client can submit blobs.",
}, null, 2));
